CREATE TABLE IF NOT EXISTS login (
    user_id INT PRIMARY KEY,
    user_pwd VARCHAR(255) NOT NULL
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS signup (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    user_pwd VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL 
)  ENGINE=INNODB;